name: Python application

on:
  push:
    branches:
      - master  # Замените на вашу ветку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 'python3.11 '  # Замените '3.x' на нужную версию Python

    - name: Create Python virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
