name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        # Добавьте здесь команды для установки зависимостей Python, если они вам нужны

    - name: Build and test with Jekyll
      env:
        JEKYLL_ENV: production
      run: |
        gem install bundler
        bundle install
        bundle exec jekyll build
