name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Setup Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        # Убедитесь, что у вас есть файл requirements.txt или укажите необходимые пакеты здесь
        pip install -r requirements.txt 

    - name: Install Jekyll and Bundler
      run: |
        gem install jekyll bundler

    - name: Build and Test Jekyll Site
      run: |
        bundle install
        bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
