name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Deploy to GitHub Pages
      run: |
         echo "::add-path::/opt/homebrew/opt/python@3.11/bin"
          echo "::set-env name=PYTHONPATH::/opt/homebrew/opt/python@3.11/bin"


