name: Build and Deploy Jekyll Site to GitHub Pages

on:
  push:
    branches: 
      - master  # Используйте нужную вам ветку

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Create and activate a Python virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
    - name: Install dependencies
      run: |
        pip install -r requirements.txt # Убедитесь, что у вас есть файл requirements.txt с зависимостями Python
    - name: Install Jekyll and dependencies
      run: |
        gem install jekyll bundler
        bundle install
    - name: Build and test the Jekyll site
      run: jekyll build
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
