name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Если ваш Jekyll проект зависит от Python, настройте его здесь
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'  # Используйте версию Python, поддерживаемую GitHub Actions

    - name: Install Jekyll dependencies
      run: |
        gem install bundler jekyll
        bundle install

    - name: Build Jekyll site
      run: |
        jekyll build
