name: Jekyll site CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Create Python virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Set up Node.js environment
      uses: actions/setup-node@v4.0.2
      with:
        node-version: '14'

    - name: Install Jekyll dependencies
      run: |
        gem install bundler jekyll
        bundle install

    - name: Build and test Jekyll site
      run: |
        jekyll build

